### ISSUE TITLE
setup.py

### ISSUE THREAD

**Issue by dfroger** [NiklasRosenstein/py-nr#2]
Hello,

My context is making a conda package for `nr`, and then for `craftr`. Here is the [recipe](https://github.com/conda-forge/staged-recipes/pull/2038), work in progress.

I have two questions/remarks about setup.py.

- If pandoc is not found, a warning message is issued, and user is asked to press  `Enter`. This make less easy to automatically execute setup.py, if pandoc is not present (which is a big dependeny, that is actually not needed in the conda packaging context). A workaround is to run `echo | python setup.py`.

- The `setup.py` makes use of the `input` function, which in Python 2 evaluate input code, and `eval('')` fails. A workaround for the previous workaround :) is `echo "1" | python setup.py`. Is `nr` intended to suppport Python 2, or just Python 3?

Maybe the `pandoc` and `input` step in `setup.py` could be made easier to work interactively?

I think the same apply for [py-require](https://github.com/conda-forge/staged-recipes/pull/2039).

**Edit:** The full command line is:

    echo "1" | python setup.py install --single-version-externally-managed --record record.txt

**Comment by dfroger** [comment]
However, `pip install .` instead of `python setup.py install` should just work.

**Comment by NiklasRosenstein** [comment]
Hey, sorry for the troubles. I implemented this as a safeguard to make sure that I don't upload a package to PyPI with no or an invalid or outdated README, since it has to be in reST format. If the `README.md` is not present, pandoc will not be invoked at all.

I could make sure that it only converts the README when it actually generates a distributable package to be uploaded to PyPI if that helps. :)

**Comment by NiklasRosenstein** [comment]
`py-require` is actually no longer needed for Craftr, I forgot to remove it from the requirements.  WIll be v2.0.0.dev5 (see https://github.com/craftr-build/craftr/issues/159)

**Comment by dfroger** [comment]
Thanks, yes, if the `readme` function would be something like this, I think it would help:

    def readme():
      if not installing: # setup.py invoked as: python setup.py install
          if os.path.isfile('README.md'):
            if os.system('pandoc -s README.md -o README.rst') != 0:
              print('-----------------------------------------------------------------')
              print('WARNING: README.rst could not be generated, pandoc command failed')
              print('-----------------------------------------------------------------')
              if sys.stdout.isatty():
                input("Enter to continue... ")

      with open('README.rst') as fp:
        return fp.read()

I'm not used to write advanced function, I'll search if there is also a good pratice for this.

**Comment by dfroger** [comment]
Ok for `py-require`. I think I'll package `craftr 1.x` too, so the conda-forge feedstock will be in place to be updated to `2.x`.

I didn't find simple solution to skip the `README.rst` generation during conda package build, so I just fork the repo for now.

**Comment by NiklasRosenstein** [comment]
Using `python setup.py install` should work without a problem now.

**Comment by NiklasRosenstein** [comment]
Should I make a new PyPI version for it or do you clone from the Git repository anyway?

**Comment by dfroger** [comment]
I can clone the Git repo. Thanks.
